packages:
  - 'frontend'
  - 'member-app'
  - 'desktop'

# Shared dependencies configuration
sharedWorkspaceFile: true

# Catalog for shared dependencies
catalog:
  react: ^18.2.0
  react-dom: ^18.2.0
  typescript: ^5.2.2
  vite: ^5.0.8
  tailwindcss: ^3.4.0
  '@types/react': ^18.2.43
  '@types/react-dom': ^18.2.17
  eslint: ^8.55.0
  '@typescript-eslint/eslint-plugin': ^6.14.0
  '@typescript-eslint/parser': ^6.14.0
  '@vitejs/plugin-react': ^4.2.1
  autoprefixer: ^10.4.16
  postcss: ^8.4.32
  '@tanstack/react-query': ^5.17.0
  '@tanstack/react-query-devtools': ^5.17.0
  react-router-dom: ^6.20.1
  zustand: ^4.4.7
  '@radix-ui/react-slot': ^1.0.2
  class-variance-authority: ^0.7.0
  clsx: ^2.0.0
  tailwind-merge: ^2.2.0
  lucide-react: ^0.303.0
  sonner: ^1.3.1