[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python start.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = {
  ENVIRONMENT = "production",
  DEBUG = "false",
  PROJECT_NAME = "GymSystem",
  DATABASE_URL = "${{ Postgres.DATABASE_URL }}",
  SECRET_KEY = "${{ secrets.SECRET_KEY }}",
  ALLOWED_ORIGINS = "https://gym-system-v6-frontend.vercel.app,http://localhost:3000,http://localhost:5173",
  USE_UVICORN = "1"
}

[environments.development]
variables = {
  ENVIRONMENT = "development",
  DEBUG = "true",
  PROJECT_NAME = "GymSystem-Dev"
}