# =============================================================================
# REGLAS DE ALERTA PARA PROMETHEUS - ARCHIVO PRINCIPAL
# Sistema de Gestión de Gimnasio v6.0
# =============================================================================

# Este archivo incluye todas las reglas de alerta organizadas por categoría
# Las reglas están divididas en archivos específicos para mejor mantenimiento

groups:
  # Incluir reglas de sistema
  - name: system_alerts
    rules: []

  # Incluir reglas de aplicación
  - name: application_alerts
    rules: []

  # Incluir reglas de infraestructura
  - name: infrastructure_alerts
    rules: []

  # Incluir reglas de negocio
  - name: business_alerts
    rules: []

  # Incluir reglas de seguridad
  - name: security_alerts
    rules: [] 