# =============================================================================
# ALERTAS DEL SISTEMA
# Sistema de Gestión de Gimnasio v6.0
# =============================================================================

groups:
  - name: system_alerts
    rules:
      # Alerta de CPU alto
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Alto uso de CPU en {{ $labels.instance }}"
          description: "El uso de CPU está por encima del 80% durante más de 5 minutos en {{ $labels.instance }}"

      # Alerta de memoria alta
      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Alto uso de memoria en {{ $labels.instance }}"
          description: "El uso de memoria está por encima del 85% durante más de 5 minutos en {{ $labels.instance }}"

      # Alerta de espacio en disco
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_avail_bytes) / node_filesystem_size_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Alto uso de disco en {{ $labels.instance }}"
          description: "El uso de disco está por encima del 85% en {{ $labels.mountpoint }} en {{ $labels.instance }}"

      # Alerta de carga del sistema
      - alert: HighSystemLoad
        expr: node_load1 > 2 * count(node_cpu_seconds_total{mode="idle"})
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Alta carga del sistema en {{ $labels.instance }}"
          description: "La carga del sistema está por encima de 2x el número de CPUs en {{ $labels.instance }}" 