# Configuraci贸n de Prometheus para Sistema de Gimnasio v6
# Monitoreo completo de aplicaci贸n, base de datos y infraestructura

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'gym-system'
    environment: 'production'

# Configuraci贸n de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Reglas de alertas
rule_files:
  - "/etc/prometheus/alert_rules.yml"

# Configuraci贸n de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Backend FastAPI
  - job_name: 'gym-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gym-backend'

  # PostgreSQL Database
  - job_name: 'gym-postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gym-postgres'

  # Redis Cache
  - job_name: 'gym-redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gym-redis'

  # Nginx Proxy
  - job_name: 'gym-nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /nginx_status
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gym-nginx'

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gym-host'

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'gym-containers' 